# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NIBM Events' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NIBM Events
  pod 'SwiftyJSON'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Kingfisher', '~> 5.9'
  pod 'GoogleSignIn'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  target 'NIBM EventsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NIBM EventsUITests' do
    # Pods for testing
  end

end
